{{- if eq .Values.secretsManager.provider "aws" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "qms-genai.name" . }}-secrets
  labels: {{- include "qms-genai.labels" . | nindent 4 }}
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: {{ include "qms-genai.name" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.secretsManager.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.secretsManager.secretName }}
        property: {{ . }}
    {{- end }}
{{- else if eq .Values.secretsManager.provider "gcp" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "qms-genai.name" . }}-secrets
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretmanager
  target:
    name: {{ include "qms-genai.name" . }}-secrets
  data:
    {{- range .Values.secretsManager.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.secretsManager.secretName }}/{{ . }}
    {{- end }}
{{- else if eq .Values.secretsManager.provider "none" }}
# secretsManager.provider=none — expect a manually-created Secret named
# "{{ include "qms-genai.name" . }}-secrets" with all keys populated.
{{- end }}
