"""baseline schema — captures current models

Revision ID: 20260804_0001
Revises:
Create Date: 2026-08-04
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "20260804_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Idempotently create the current schema.

    We ``create_all`` from live metadata so a Postgres deploy that
    already has tables (bootstrapped by an older SQLite build) does
    not error out. Subsequent revisions can be autogenerated normally.
    """
    from database import Base
    import models  # noqa: F401 registers mappers

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind, checkfirst=True)


def downgrade() -> None:
    from database import Base
    import models  # noqa: F401

    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
