# services/tasks.py
# ─────────────────────────────────────────────────────────
# CELERY TASKS — async CAPA generation
# Reuses the existing generate → save → embed pipeline.
# ─────────────────────────────────────────────────────────

from datetime import datetime, timedelta

from services.agents.orchestrator import new_capa_id
from services.celery_app import celery_app
from services.logging_config import get_logger

log = get_logger(__name__)


_TYPE_LABEL = {
    "complaint": "Complaint",
    "deviation": "Deviation",
    "cc": "Change Control",
    "nc": "Non-Conformance",
    "audit": "Audit",
}


@celery_app.task(name="qms.generate_capa_async", bind=True)
def generate_capa_async(self, record_id: str, actor: dict = None) -> dict:
    """
    Async: generate a CAPA for one record, save it, embed it for RAG.
    Returns a small status dict. Never raises out of the task —
    failures are captured in the return payload.
    """
    try:
        from data.records import get_record_by_id, save_capa, update_record_status
        from services.ai_service import generate_capa

        record = get_record_by_id(record_id)
        if not record:
            return {"record_id": record_id, "status": "error",
                    "error": "record not found"}

        capa_data = generate_capa(record)
        capa_id = new_capa_id()
        now = datetime.now().isoformat()
        closure = int(capa_data.get("estimatedClosureDays", 30))
        actor = actor or {}
        capa = {
            "capaId":               capa_id,
            "status":               "Under Review",
            "sourceRecordId":       record_id,
            "sourceRecordType":     _TYPE_LABEL.get(record.get("type", ""), "—"),
            "sourceRecordTitle":    record.get("title", "—"),
            "sector":               record.get("sector", "—"),
            "priority":             record.get("priority", "—"),
            "site":                 record.get("site", "—"),
            "rootCause":            capa_data.get("rootCause", ""),
            "immediateAction":      capa_data.get("immediateAction", ""),
            "correctiveAction":     capa_data.get("correctiveAction", ""),
            "preventiveAction":     capa_data.get("preventiveAction", ""),
            "capaOwner":            capa_data.get("proposedOwner", ""),
            "effectivenessCheck":   capa_data.get("effectivenessCheck", ""),
            "riskRating":           capa_data.get("riskRating", record.get("priority", "")),
            "regulatoryRef":        capa_data.get("regulatoryRef", record.get("regulatoryRef", [])),
            "estimatedClosureDays": closure,
            "targetClosureDate":    (datetime.now() + timedelta(days=closure)).strftime("%Y-%m-%d"),
            "notes":                "Auto-generated by batch agent",
            "createdBy":            actor.get("full_name", ""),
            "createdByUsername":    actor.get("username", ""),
            "createdByRole":        actor.get("role", ""),
            "createdAt":            now,
            "updatedAt":            now,
        }
        saved = save_capa(capa)
        capa_id = saved.get("capaId") if isinstance(saved, dict) else capa_id
        update_record_status(record_id, "Under Review")

        # Embed into vector store (non-blocking, best effort)
        try:
            from services.vector_store import embed_capa
            embed_capa(capa)
        except Exception:
            log.warning("tasks.embed_skipped", exc_info=True,
                        extra={"capa_id": capa_id, "record_id": record_id})

        return {"record_id": record_id, "status": "done", "capaId": capa_id}
    except Exception as exc:
        log.exception("tasks.generate_capa_failed", extra={"record_id": record_id})
        return {"record_id": record_id, "status": "error", "error": str(exc)}


@celery_app.task(name="qms.agent_supervisor_run", bind=True)
def agent_supervisor_run(self) -> dict:
    """Scheduled autonomous agent scan. Intended for Celery Beat every 20 minutes."""
    try:
        from config import AGENT_SUPERVISOR_ALLOW_WEEKEND, AGENT_SUPERVISOR_LIMIT
        from services.agents.supervisor import AgentSupervisor

        return AgentSupervisor().run_once(
            triggered_by="celery-beat",
            limit=AGENT_SUPERVISOR_LIMIT,
            allow_weekend=AGENT_SUPERVISOR_ALLOW_WEEKEND,
        )
    except Exception as exc:
        log.exception("tasks.agent_supervisor_failed")
        return {"status": "error", "error": str(exc)}
